# Variables
@base_url = http://localhost:3333

# Health check
# @name healthCheck
GET {{base_url}}/health

###

# GET rooms
# @name getRooms
GET {{base_url}}/rooms

###

# Create room
# @name createRoom
POST {{base_url}}/rooms
Content-Type: application/json

{
  "name": "Sala de teste",
  "description": "Essa é uma sala de teste!"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get room questions
# @name getRoomQuestions
GET {{base_url}}/rooms/{{roomId}}/questions

###

# Create question
# @name createQuestion
POST {{base_url}}/rooms/{{roomId}}/questions
Content-Type: application/json

{
  "question": "Qual é o conceito de X dentro de Y?"
}